// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebRadio.Infrastructure.Persistencia;

#nullable disable

namespace WebRadio.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(RadioDbContext))]
    partial class RadioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebRadio.Domain.Autenticacao.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_RefreshToken_Id");

                    b.Property<DateTime>("CriadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_RefreshToken_CriadoEmUtc");

                    b.Property<byte[]>("CriadoPorIpHash")
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("ExpiraEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevogadoEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_RefreshToken");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("IX_RefreshToken_FamiliaId")
                        .HasFilter("RevogadoEmUtc IS NULL");

                    b.HasIndex("SubstituidoPorId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshToken_TokenHash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_RefreshToken_UsuarioId");

                    b.ToTable("RefreshToken", "seg", t =>
                        {
                            t.HasCheckConstraint("CK_RefreshToken_Expira", "ExpiraEmUtc > CriadoEmUtc");
                        });
                });

            modelBuilder.Entity("WebRadio.Domain.Grade.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_Programa_Id");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_Programa_AtualizadoEmUtc");

                    b.Property<DateTime?>("CanceladoEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_Programa_CriadoEmUtc");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FimUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("LocutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_Programa_Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id")
                        .HasName("PK_Programa");

                    b.HasIndex("InicioUtc")
                        .HasDatabaseName("IX_Programa_Grade");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("InicioUtc"), new[] { "FimUtc", "Status", "Titulo", "LocutorId" });

                    b.HasIndex("LocutorId")
                        .HasDatabaseName("IX_Programa_LocutorId");

                    b.HasIndex("Status", "InicioUtc")
                        .HasDatabaseName("IX_Programa_Worker")
                        .HasFilter("Status IN (1, 2)");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "InicioUtc"), new[] { "FimUtc" });

                    b.ToTable("Programa", "grade", t =>
                        {
                            t.HasCheckConstraint("CK_Programa_Cancelado", "(Status = 4 AND CanceladoEmUtc IS NOT NULL) OR (Status <> 4 AND CanceladoEmUtc IS NULL)");

                            t.HasCheckConstraint("CK_Programa_DuracaoMax", "DATEDIFF(MINUTE, InicioUtc, FimUtc) <= 720");

                            t.HasCheckConstraint("CK_Programa_Intervalo", "FimUtc > InicioUtc");

                            t.HasCheckConstraint("CK_Programa_Status", "Status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("WebRadio.Domain.Interacao.Divulgacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_Divulgacao_Id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Divulgacao_Ativo");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_Divulgacao_AtualizadoEmUtc");

                    b.Property<DateTime>("CriadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_Divulgacao_CriadoEmUtc");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FimExibicaoUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ImagemChaveStorage")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("InicioExibicaoUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LinkDestino")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("Prioridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)50, "DF_Divulgacao_Prioridade");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id")
                        .HasName("PK_Divulgacao");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Prioridade")
                        .IsDescending()
                        .HasDatabaseName("IX_Divulgacao_Ativas")
                        .HasFilter("Ativo = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Prioridade"), new[] { "Titulo", "Mensagem", "ImagemChaveStorage", "LinkDestino", "InicioExibicaoUtc", "FimExibicaoUtc" });

                    b.ToTable("Divulgacao", "interacao", t =>
                        {
                            t.HasCheckConstraint("CK_Divulgacao_Janela", "InicioExibicaoUtc IS NULL OR FimExibicaoUtc IS NULL OR FimExibicaoUtc > InicioExibicaoUtc");

                            t.HasCheckConstraint("CK_Divulgacao_Link", "LinkDestino IS NULL OR LinkDestino LIKE 'https://%'");

                            t.HasCheckConstraint("CK_Divulgacao_Prioridade", "Prioridade BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("WebRadio.Domain.Interacao.PedidoMusica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_PedidoMusica_Id");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_PedidoMusica_CriadoEmUtc");

                    b.Property<DateTime?>("EnviadoPlayoutEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("ListenerDeviceHash")
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("ListenerIpHash")
                        .HasColumnType("binary(32)");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<Guid?>("MidiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModeradoEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("ModeradoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<string>("NomeOuvinte")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid?>("ProgramaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_PedidoMusica_Status");

                    b.Property<string>("TituloMusica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TocadoEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_PedidoMusica");

                    b.HasIndex("CriadoEmUtc")
                        .HasDatabaseName("IX_PedidoMusica_Fila")
                        .HasFilter("Status = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CriadoEmUtc"), new[] { "NomeOuvinte", "TituloMusica", "Artista", "Mensagem", "ProgramaId" });

                    b.HasIndex("MidiaId")
                        .HasDatabaseName("IX_PedidoMusica_MidiaId")
                        .HasFilter("MidiaId IS NOT NULL");

                    b.HasIndex("ModeradoEmUtc")
                        .HasDatabaseName("IX_PedidoMusica_Playout")
                        .HasFilter("Status = 2 AND MidiaId IS NOT NULL AND EnviadoPlayoutEmUtc IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ModeradoEmUtc"), new[] { "MidiaId" });

                    b.HasIndex("ModeradoPorUsuarioId");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("IX_PedidoMusica_ProgramaId")
                        .HasFilter("ProgramaId IS NOT NULL");

                    b.HasIndex("ListenerDeviceHash", "CriadoEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PedidoMusica_Device")
                        .HasFilter("ListenerDeviceHash IS NOT NULL");

                    b.HasIndex("ListenerIpHash", "CriadoEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PedidoMusica_Ip")
                        .HasFilter("ListenerIpHash IS NOT NULL");

                    b.HasIndex("UsuarioId", "CriadoEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PedidoMusica_Usuario")
                        .HasFilter("UsuarioId IS NOT NULL");

                    b.ToTable("PedidoMusica", "interacao", t =>
                        {
                            t.HasCheckConstraint("CK_PedidoMusica_Moderacao", "Status NOT IN (2, 3, 4) OR (ModeradoPorUsuarioId IS NOT NULL AND ModeradoEmUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_PedidoMusica_Rejeicao", "Status <> 3 OR MotivoRejeicao IS NOT NULL");

                            t.HasCheckConstraint("CK_PedidoMusica_Status", "Status IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_PedidoMusica_Tocado", "Status <> 4 OR TocadoEmUtc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("WebRadio.Domain.Midia.ArquivoMidia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_ArquivoMidia_Id");

                    b.Property<string>("Artista")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_ArquivoMidia_Ativo");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("varchar(63)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ChaveStorage")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("DataUploadUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_ArquivoMidia_DataUploadUtc");

                    b.Property<decimal?>("DuracaoSegundos")
                        .HasColumnType("decimal(9,3)");

                    b.Property<DateTime?>("EmAnaliseDesdeUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("EnviadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EtagUpload")
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("HashOriginalSHA256")
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("HashSHA256")
                        .HasColumnType("binary(32)");

                    b.Property<string>("MimeType")
                        .HasColumnType("varchar(100)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("MimeTypeDeclarado")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SanitizadoEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("StatusSanitizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_ArquivoMidia_Status");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<byte>("TentativasSanitizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0, "DF_ArquivoMidia_TentativasSanitizacao");

                    b.Property<byte>("TipoMidia")
                        .HasColumnType("tinyint");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadExpiraEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id")
                        .HasName("PK_ArquivoMidia");

                    b.HasIndex("EnviadoPorUsuarioId")
                        .HasDatabaseName("IX_ArquivoMidia_EnviadoPor");

                    b.HasIndex("HashOriginalSHA256")
                        .HasDatabaseName("IX_ArquivoMidia_HashOriginal")
                        .HasFilter("HashOriginalSHA256 IS NOT NULL");

                    b.HasIndex("HashSHA256")
                        .IsUnique()
                        .HasDatabaseName("UX_ArquivoMidia_Hash_Aprovado")
                        .HasFilter("StatusSanitizacao = 4 AND HashSHA256 IS NOT NULL");

                    b.HasIndex("Bucket", "ChaveStorage")
                        .IsUnique()
                        .HasDatabaseName("UX_ArquivoMidia_Objeto");

                    b.HasIndex("StatusSanitizacao", "DataUploadUtc")
                        .HasDatabaseName("IX_ArquivoMidia_FilaSanitizacao")
                        .HasFilter("StatusSanitizacao IN (1, 2, 3)");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StatusSanitizacao", "DataUploadUtc"), new[] { "UploadExpiraEmUtc", "TentativasSanitizacao", "EmAnaliseDesdeUtc" });

                    b.HasIndex("TipoMidia", "StatusSanitizacao")
                        .HasDatabaseName("IX_ArquivoMidia_Biblioteca");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TipoMidia", "StatusSanitizacao"), new[] { "Titulo", "Artista", "DuracaoSegundos", "Ativo" });

                    b.ToTable("ArquivoMidia", "midia", t =>
                        {
                            t.HasCheckConstraint("CK_ArquivoMidia_AprovadoCompleto", "StatusSanitizacao <> 4 OR (MimeType IS NOT NULL AND HashSHA256 IS NOT NULL AND DuracaoSegundos IS NOT NULL AND SanitizadoEmUtc IS NOT NULL AND Bucket = 'midia')");

                            t.HasCheckConstraint("CK_ArquivoMidia_Bucket", "Bucket IN ('quarentena', 'midia')");

                            t.HasCheckConstraint("CK_ArquivoMidia_Duracao", "DuracaoSegundos IS NULL OR DuracaoSegundos > 0");

                            t.HasCheckConstraint("CK_ArquivoMidia_EmAnalise", "StatusSanitizacao <> 3 OR EmAnaliseDesdeUtc IS NOT NULL");

                            t.HasCheckConstraint("CK_ArquivoMidia_MimeType", "MimeType IS NULL OR MimeType IN ('audio/mpeg', 'audio/ogg', 'audio/wav', 'audio/flac')");

                            t.HasCheckConstraint("CK_ArquivoMidia_Musica_Titulo", "TipoMidia <> 3 OR Titulo IS NOT NULL");

                            t.HasCheckConstraint("CK_ArquivoMidia_Status", "StatusSanitizacao IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("CK_ArquivoMidia_Tamanho", "TamanhoBytes > 0 AND TamanhoBytes <= 262144000");

                            t.HasCheckConstraint("CK_ArquivoMidia_TentativasSanitizacao", "TentativasSanitizacao BETWEEN 0 AND 10");

                            t.HasCheckConstraint("CK_ArquivoMidia_Tipo", "TipoMidia IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("WebRadio.Domain.Midia.Reproducao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("IniciadoEmUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("MidiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Reproducao");

                    b.HasIndex("IniciadoEmUtc")
                        .HasDatabaseName("IX_Reproducao_Periodo");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IniciadoEmUtc"), new[] { "MidiaId" });

                    b.HasIndex("MidiaId")
                        .HasDatabaseName("IX_Reproducao_MidiaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProgramaId");

                    b.ToTable("Reproducao", "midia");
                });

            modelBuilder.Entity("WebRadio.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()", "DF_Usuario_Id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Usuario_Ativo");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_Usuario_AtualizadoEmUtc");

                    b.Property<DateTime>("CriadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_Usuario_CriadoEmUtc");

                    b.Property<bool>("DeveTrocarSenha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Usuario_DeveTrocarSenha");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id")
                        .HasName("PK_Usuario");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuario_EmailNormalizado");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Usuario_Role");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Role"), new[] { "Nome", "Ativo" });

                    b.ToTable("Usuario", "seg", t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Role", "Role IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("WebRadio.Infrastructure.Persistencia.Outbox.EventoOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()", "DF_EventoOutbox_CriadoEmUtc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessadoEmUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<short>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0, "DF_EventoOutbox_Tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_EventoOutbox");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_EventoOutbox_Pendentes")
                        .HasFilter("ProcessadoEmUtc IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "Tentativas" });

                    b.ToTable("EventoOutbox", "infra", t =>
                        {
                            t.HasCheckConstraint("CK_EventoOutbox_Payload", "ISJSON(Payload) = 1");
                        });
                });

            modelBuilder.Entity("WebRadio.Domain.Autenticacao.RefreshToken", b =>
                {
                    b.HasOne("WebRadio.Domain.Autenticacao.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("SubstituidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RefreshToken_SubstituidoPor");

                    b.HasOne("WebRadio.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_Usuario");
                });

            modelBuilder.Entity("WebRadio.Domain.Grade.Programa", b =>
                {
                    b.HasOne("WebRadio.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("LocutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Programa_Locutor");
                });

            modelBuilder.Entity("WebRadio.Domain.Interacao.Divulgacao", b =>
                {
                    b.HasOne("WebRadio.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Divulgacao_CriadoPor");
                });

            modelBuilder.Entity("WebRadio.Domain.Interacao.PedidoMusica", b =>
                {
                    b.HasOne("WebRadio.Domain.Midia.ArquivoMidia", null)
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PedidoMusica_Midia");

                    b.HasOne("WebRadio.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ModeradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PedidoMusica_ModeradoPor");

                    b.HasOne("WebRadio.Domain.Grade.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PedidoMusica_Programa");

                    b.HasOne("WebRadio.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PedidoMusica_Usuario");
                });

            modelBuilder.Entity("WebRadio.Domain.Midia.ArquivoMidia", b =>
                {
                    b.HasOne("WebRadio.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EnviadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ArquivoMidia_EnviadoPor");
                });

            modelBuilder.Entity("WebRadio.Domain.Midia.Reproducao", b =>
                {
                    b.HasOne("WebRadio.Domain.Midia.ArquivoMidia", null)
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reproducao_Midia");

                    b.HasOne("WebRadio.Domain.Interacao.PedidoMusica", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Reproducao_Pedido");

                    b.HasOne("WebRadio.Domain.Grade.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Reproducao_Programa");
                });
#pragma warning restore 612, 618
        }
    }
}
